### ISSUE TITLE
No support for VSCode actions

### ISSUE THREAD

**Issue by mkasprz** [BouKiCHi/vscode-watch-run#1]
Hi.
Firstly, I thought this extension is all about execution VSCode actions. Now I know it's not, but I believe it could be quite useful feature. I personally wanted to use it to restart debugging session when specific file changed.

**Comment by BouKiCHi** [comment]
Hi,
Thank you for your opinion.
I would like to consider whether there is an implementation method for VSCode command execution.

**Comment by mkasprz** [comment]
Thank You for the answer.
Isn't it what You would need: https://code.visualstudio.com/docs/extensionAPI/vscode-api#1795 (`executeCommand` method)?
