### ISSUE TITLE
".vscode/finished-tasks" as `target` doesn't work

### ISSUE THREAD

**Issue by mkasprz** [BouKiCHi/vscode-watch-run#2]
Hi.
I tried setting ".vscode/finished-tasks", "./.vscode/finished-tasks" and, I believe, even "**/finished-tasks" as `target` and changing that file didn't tigger any action. Is it intentional?

('finished-tasks' is just a regular text file.)

**Comment by BouKiCHi** [comment]
Hi,
README.md was unclear, It has been rewritten.
The  target is the task name of tasks.json.

**Comment by mkasprz** [comment]
Thank You.
Are You sure about that? `"target": "**/*.mml",` doesn't look like a task name.
I believe You meant that `task` defines the name of the task and `target` the files which change will trigger the task. Such file could be referenced as `${file}` in the `cmd`. Am I right?

**Comment by BouKiCHi** [comment]
Hi,
Sorry, I was wrong. You are right.
It was a bug of extension and already updated.
If I remember correct, ${file} is the path of current editing file.

Thanks.

**Comment by mkasprz** [comment]
I'm glad we agreed at the end.
Thank You.
