### ISSUE TITLE
Does not support multiple folders paths from workspace

### ISSUE THREAD

**Issue by pr-yemibedu** [BouKiCHi/vscode-watch-run#3]
Hello,
Using version : 1.28.1
Platform: WIndows 10

 I have a workspace looking at two folders and all the task and changes from only one is being applied. Can this be made to be workspace friendly? Thank you. Good day.

**Comment by pr-yemibedu** [comment]
Hello,
 Please check out the MS official [Extension Authoring Adopting MRW API](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) to see the small changes to make this work. It is only a loop for the workspace folders and a refactor to call an indirect function for each folder.
 You would possibly want to check if the user wants it to apply to all folders, a named folder, a folder index, or none. That could be added to the settings. Thank you. Good day.

**Comment by BouKiCHi** [comment]
Thanks!
I'll check the document and I would like to fix the issue.

**Comment by BouKiCHi** [comment]
The update has been released.
Thanks.
