### ISSUE TITLE
Changed file variable

### ISSUE THREAD

**Issue by ghost** [BouKiCHi/vscode-watch-run#6]
Thank you for this extension!
Is there a variable that I can use in tasks configuration to catch what's file have been changed?

**Comment by BouKiCHi** [comment]
${file} in tasks.json is the file which has been changed .

        {
            "label": "show_filename",
            "type": "shell",
            "command": "echo \"File:${file}\""
        }

**Comment by ghost** [comment]
${file} always give me the current file in vscode :(

**Comment by BouKiCHi** [comment]
ah, It may be difficult for now.
I think the pattern is like you didn't save the current file in vscode.

**Comment by ghost** [comment]
Exactly, this is a Qt ui file. I would like to track change on this file to compile it.
Thanks anyway for your quick response.

**Comment by BouKiCHi** [comment]
added a way to get the path of changed file. 
thanks ;)
